version: '3.7'

services:
  frontend:
    container_name: frontend
    build:
      context: ./react-shop
      dockerfile: Dockerfile
    volumes:
      - './react-shop:/app/front'
      - '/app/front/node_modules'
    ports:
      - "3000:3000"


  backend:
    container_name: backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    volumes:
      - ./Backend:/app/back
    ports:
      - "8000:8000"