# Generated by Django 4.0.1 on 2022-01-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcart',
            name='product',
        ),
        migrations.AddField(
            model_name='productcart',
            name='product',
            field=models.ManyToManyField(to='Shop.Product'),
        ),
    ]
